# Generated by Django 4.1 on 2024-03-13 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bank", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customers",
            old_name="Customer_name",
            new_name="Customer_NAME",
        ),
        migrations.AlterField(
            model_name="customers",
            name="Aadhar_number",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="customers",
            name="Account_no",
            field=models.IntegerField(
                auto_created="True", primary_key="True", serialize=False
            ),
        ),
    ]
