# Generated by Django 4.1 on 2024-03-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bank", "0002_rename_customer_name_customers_customer_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customers",
            name="Account_no",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
