# Generated by Django 4.1 on 2024-03-15 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bank", "0003_alter_customers_account_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customers",
            name="Balance",
            field=models.IntegerField(default=500),
        ),
    ]
