# Generated by Django 4.1 on 2024-03-18 04:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bank", "0004_alter_customers_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customers",
            name="Aadhar_number",
            field=models.IntegerField(unique="True"),
        ),
        migrations.AlterField(
            model_name="customers",
            name="Balance",
            field=models.DecimalField(decimal_places=2, default=500, max_digits=20),
        ),
    ]
