# Generated by Django 4.1 on 2024-03-27 04:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bank", "0005_alter_customers_aadhar_number_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customers",
            old_name="Date_of_opening",
            new_name="Date_of_Opening",
        ),
    ]
