# Generated by Django 4.1 on 2024-03-27 04:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bank", "0006_rename_date_of_opening_customers_date_of_opening"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customers",
            old_name="Customer_NAME",
            new_name="customer_name",
        ),
        migrations.AlterField(
            model_name="customers",
            name="Aadhar_number",
            field=models.IntegerField(unique=True),
        ),
    ]
