# Generated by Django 4.1 on 2024-05-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bank", "0007_rename_customer_name_customers_customer_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="user",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254)),
                ("phonenumber", models.CharField(max_length=10)),
                ("password", models.CharField(max_length=15)),
                ("repassword", models.CharField(max_length=15)),
            ],
        ),
    ]
