# Generated by Django 4.1 on 2024-05-17 06:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bank", "0008_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customers",
            old_name="customer_name",
            new_name="Customer_NAME",
        ),
    ]
